name: "driver_config"
description: "Runs a wind, pv, and battery plant with optimization"

general:
  folder_output: wind_pv_battery_run

driver:
  optimization:
    flag: True
    tol: 0.1
    max_iter: 100
    solver: COBYLA
    rhobeg: 1000.
    debug_print: True

design_variables:
  hybrid:
    wind_turbine_rating_kw:
      flag: True
      lower: 0.0
      upper: 5.
      units: MW
    pv_capacity_kw:
      flag: True
      lower: 0.0
      upper: 22.
      units: MW
    battery_capacity_kw:
      flag: True
      lower: 0.0
      upper: 22.
      units: MW
    battery_capacity_kwh:
      flag: True
      lower: 0.0
      upper: 22.
      units: MW*h

constraints:
  hybrid:
    percent_load_missed:
      flag: False
      lower: 20.
      units: percent
    curtailment_percent:
      flag: False
      lower: 20.0
      units: percent
    battery_duration:
      flag: True
      upper: 10
      units: h
    power_capacity_to_interconnect_ratio:
      flag: True
      lower: 0.2
      units: unitless
    annual_energy_to_interconnect_potential_ratio:
      flag: True
      lower: 0.2
      units: unitless

objective:
  name: plant.financials_group_profast.profast_comp_0.LCOE
