"""Guard documentation references against the current model and repository layout."""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from ruamel.yaml import YAML
from ruamel.yaml.error import YAMLError
from ruamel.yaml.nodes import ScalarNode, MappingNode, SequenceNode

from h2integrate.core.supported_models import supported_models


pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = REPO_ROOT / "docs"
EXAMPLES_ROOT = REPO_ROOT / "examples"
MODEL_KEYS = {"model", "resource_model", "finance_model", "control_strategy"}
MODEL_FENCE_RE = re.compile(r"(?ms)^```(?:yaml|yml)\s*\n(.*?)^```")
REPOSITORY_PATH_RE = re.compile(r"\b(?:examples|h2integrate|library)/[A-Za-z0-9_./*{}-]+")
URL_RE = re.compile(r"https?://\S+")

# Keep these lists current as model pages and example references are added.
UNDOCUMENTED_MODELS = {
    "PyomoDispatchGenericConverterMinOperatingCosts",
    "PyomoRuleStorageMinOperatingCosts",
    "SimpleCycleTurbinePerformanceModel",
    "GenericConverterCostModel",
    "IronTransportPerformanceComponent",
    "IronTransportCostComponent",
    "CO2HMethanolPlantPerformanceModel",
    "CO2HMethanolPlantCostModel",
    "CO2HMethanolPlantFinanceModel",
    "SMRMethanolPlantPerformanceModel",
    "SMRMethanolPlantFinanceModel",
    "SteelPerformanceModel",
    "SimpleASUPerformanceModel",
    "ReverseOsmosisPerformanceModel",
    "RiverResource",
    "TidalResource",
    "GasStreamCombinerPerformanceModel",
    "LinearMassTransportCostModel",
    "StorageAutoSizingModel",
    "SimpleGasProducerPerformance",
    "SimpleGasProducerCost",
    "SimpleGasConsumerPerformance",
    "SimpleGasConsumerCost",
}
UNREFERENCED_EXAMPLES = {"04_geo_h2", "31_tidal", "36_nuclear_reactor_htse"}
CUSTOM_MODEL_NAMES = {"CustomRiverResource", "SimpleLCOFinance"}
KNOWN_MISSING_PATHS = set()


def _markdown_pages() -> list[Path]:
    return [
        path
        for path in DOCS_ROOT.rglob("*.md")
        if not {"_build", "_autosummary"}.intersection(path.relative_to(DOCS_ROOT).parts)
        and path.name != "model_registry.md"
    ]


def _page_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    return re.sub(
        r"(?s)<!-- BEGIN_AUTOGENERATED_MODEL_REGISTRY -->.*?"
        r"<!-- END_AUTOGENERATED_MODEL_REGISTRY -->",
        "",
        text,
    )


def _construct_tagged_yaml(constructor, _tag_suffix, node):
    if isinstance(node, ScalarNode):
        return constructor.construct_scalar(node)
    if isinstance(node, SequenceNode):
        return constructor.construct_sequence(node, deep=True)
    if isinstance(node, MappingNode):
        return constructor.construct_mapping(node, deep=True)
    raise TypeError(f"Unsupported YAML node: {type(node).__name__}")


def _yaml_values(value):
    if isinstance(value, dict):
        for key, child in value.items():
            if key in MODEL_KEYS and isinstance(child, str):
                yield key, child
            yield from _yaml_values(child)
    elif isinstance(value, list):
        for child in value:
            yield from _yaml_values(child)


def _model_references(text: str):
    for match in MODEL_FENCE_RE.finditer(text):
        parser = YAML(typ="safe")
        parser.constructor.add_multi_constructor("!", _construct_tagged_yaml)
        try:
            document = parser.load(match.group(1))
        except YAMLError:
            continue
        yield from _yaml_values(document)


def test_yaml_model_references_are_registered():
    """Prevent copyable YAML examples from naming models users cannot configure.

    Parse fenced YAML, recursively inspect model-valued keys, and compare each name
    with the model registry, allowing explicitly listed custom models.
    """
    unknown = []
    for page in _markdown_pages():
        for key, name in _model_references(_page_text(page)):
            if name not in supported_models and name not in CUSTOM_MODEL_NAMES:
                unknown.append(f"{page.relative_to(REPO_ROOT)}: {key}: {name}")

    assert not unknown, "Unregistered model names in YAML fences:\n" + "\n".join(unknown)


def test_repository_paths_in_docs_exist():
    """Catch stale repository paths that would send readers to missing files.

    Remove external URLs, scan Markdown for repository path references, and check
    each file, Python-module shorthand, or glob against the checkout.
    """
    missing = []
    for page in _markdown_pages():
        page_path = page.relative_to(REPO_ROOT).as_posix()
        text = URL_RE.sub(" ", _page_text(page))
        for match in REPOSITORY_PATH_RE.finditer(text):
            reference = match.group(0).rstrip(".,;:")
            if any(character in reference for character in "*{}"):
                exists = any(REPO_ROOT.glob(reference))
            else:
                target = REPO_ROOT / reference
                exists = target.exists() or (
                    not target.suffix and target.with_suffix(".py").exists()
                )
            if not exists:
                missing.append((page_path, reference))

    assert set(missing) == KNOWN_MISSING_PATHS, (
        "Update the docs or repository-path allowlist: "
        f"unexpected={sorted(set(missing) - KNOWN_MISSING_PATHS)}, "
        f"resolved={sorted(KNOWN_MISSING_PATHS - set(missing))}"
    )


def test_registered_models_have_narrative_documentation():
    """Keep registered models discoverable in user-facing documentation.

    Search Markdown outside the generated model registry for every registered
    model name, excluding only models tracked in the undocumented-model allowlist.
    """
    text = "\n".join(_page_text(page) for page in _markdown_pages())
    undocumented = {
        name
        for name in supported_models
        if name not in UNDOCUMENTED_MODELS
        and not re.search(rf"(?<![A-Za-z0-9_]){re.escape(name)}(?![A-Za-z0-9_])", text)
    }

    assert undocumented == set(), (
        "New registered models need narrative documentation or an explicit allowlist entry: "
        f"{sorted(undocumented)}"
    )


def test_example_folders_are_referenced_from_docs():
    """Ensure numbered runnable examples can be found through the documentation.

    Compare numbered example directories with names mentioned in Markdown, and
    permit only the example folders recorded in the unreferenced-example allowlist.
    """
    text = "\n".join(_page_text(page) for page in _markdown_pages())
    example_folders = {
        path.name
        for path in EXAMPLES_ROOT.iterdir()
        if path.is_dir() and re.match(r"^\d{2}_", path.name)
    }
    unreferenced = {name for name in example_folders if name not in text}

    assert unreferenced == UNREFERENCED_EXAMPLES, (
        f"Update the docs or the known example-reference allowlist: {sorted(unreferenced)}"
    )
